[package]
name = "portman-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "CLI tool for Portman, checking local ports and managing labels on macOS."
readme = "../../README.md"
keywords = ["port", "cli", "macos", "development", "network"]
categories = ["command-line-utilities"]
default-run = "portman"

[[bin]]
name = "portman"
path = "src/main.rs"

[dependencies]
portman-core = { path = "../portman_core", version = "0.1.0" }
clap = { version = "4.4", features = ["derive"] }
comfy-table = "7.1"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
colored = "2.0"
chrono = "0.4.43"
